### PR TITLE
Added the original chart for "If I Needed Someone".

### PR DESCRIPTION
**Pull request by beatlegoose**

### CODE REVIEW

**Comment by iamSynchrony** [comment]
why did you replace the chart?

**Comment by beatlegoose** [comment]
Fixed my mistake.

**Comment by iamSynchrony** [comment]
looks good now other than it being under rubber soul and downloaded being false (will cause issues in online play)

**Comment by beatlegoose** [comment]
Resolved

**Comment by iamSynchrony** [comment]
everything is good now. merging

**Pull request merged**
